name: deploy

on:
  workflow_dispatch:
    inputs:
      scenario:
        type: string
        required: true
        description: "Scenario to deploy"
        default: "tfstate_backend"
      environment:
        type: environment
        required: true
        description: "Environment to deploy"
        default: "ci"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: deploy scenario
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            cd infra
            make deploy SCENARIO=${{ github.event.inputs.scenario }}
