name: infra

on:
  push:
    paths:
      - infra/**
    branches:
      - main
  schedule:
    - cron: "00 00 * * 3"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    environment: ci
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: run CI tests
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            cd infra
            make ci-test
