name: test

on:
  push:
    paths:
      - infra/**
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd infra && make ci-test
